export { HomeComponent } from './home/home.component';
export { Ex01Component } from './ex01/ex01.component';
export { Ex02Component } from './ex02/ex02.component';
export { Ex03Component } from './ex03/ex03.component';
export { Ex04Component } from './ex04/ex04.component';
export { Ex05Component } from './ex05/ex05.component';
export { Ex06Component } from './ex06/ex06.component';
export { Ex07Component } from './ex07/ex07.component';
export { Ex08Component } from './ex08/ex08.component';
export { Ex10Component } from './ex10/ex10.component';
export * from './ex09/ex09.component';
export * from './exam/exam.component';
